# Generated by Django 4.2.4 on 2023-08-29 17:31

from django.db import migrations, models
import olympiad.validators


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[olympiad.validators.validate_min_length], verbose_name='Номер телефона'),
        ),
    ]
